package com.example.extdannyjiang.greendaodemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.extdannyjiang.greendaodemo.dao_bean.MyOrder;
import com.example.extdannyjiang.greendaodemo.dao_bean.User;

import com.example.extdannyjiang.greendaodemo.dao.MyOrderDao;
import com.example.extdannyjiang.greendaodemo.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myOrderDaoConfig;
    private final DaoConfig userDaoConfig;

    private final MyOrderDao myOrderDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myOrderDaoConfig = daoConfigMap.get(MyOrderDao.class).clone();
        myOrderDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        myOrderDao = new MyOrderDao(myOrderDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(MyOrder.class, myOrderDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        myOrderDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public MyOrderDao getMyOrderDao() {
        return myOrderDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
