package com.example.extdannyjiang.greendaodemo.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.example.extdannyjiang.greendaodemo.dao_bean.MyOrder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MY_ORDER".
*/
public class MyOrderDao extends AbstractDao<MyOrder, Long> {

    public static final String TABLENAME = "MY_ORDER";

    /**
     * Properties of entity MyOrder.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Date = new Property(1, String.class, "date", false, "date");
        public final static Property CustomId = new Property(2, Long.class, "customId", false, "customId");
    }

    private Query<MyOrder> user_OrdersQuery;

    public MyOrderDao(DaoConfig config) {
        super(config);
    }
    
    public MyOrderDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MY_ORDER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"date\" TEXT," + // 1: date
                "\"customId\" INTEGER);"); // 2: customId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MY_ORDER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MyOrder entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(2, date);
        }
 
        Long customId = entity.getCustomId();
        if (customId != null) {
            stmt.bindLong(3, customId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MyOrder entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(2, date);
        }
 
        Long customId = entity.getCustomId();
        if (customId != null) {
            stmt.bindLong(3, customId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MyOrder readEntity(Cursor cursor, int offset) {
        MyOrder entity = new MyOrder( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // date
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // customId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MyOrder entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCustomId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MyOrder entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MyOrder entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MyOrder entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "orders" to-many relationship of User. */
    public List<MyOrder> _queryUser_Orders(Long customId) {
        synchronized (this) {
            if (user_OrdersQuery == null) {
                QueryBuilder<MyOrder> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CustomId.eq(null));
                user_OrdersQuery = queryBuilder.build();
            }
        }
        Query<MyOrder> query = user_OrdersQuery.forCurrentThread();
        query.setParameter(0, customId);
        return query.list();
    }

}
